apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
      - name: anime-container
        image: gcr.io/my-project-01-452610/anime-recs:latest
        ports:
        - containerPort: 8000 
---
apiVersion: v1
kind: Service
metadata:
  name: anime-service
spec:
  type: LoadBalancer
  selector:
    app: anime
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
