apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-recs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anime-recs
  template:
    metadata:
      labels:
        app: anime-recs
    spec:
      containers:
      - name: anime-recs-container
        image: gcr.io/my-project-01-452610/anime-recs:latest
        ports:
        - containerPort: 8000 
---
apiVersion: v1
kind: Service
metadata:
  name: anime-recs-service
spec:
  type: LoadBalancer
  selector:
    app: anime-recs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
